[colors]
ansi = [
    'hsla(32, 48%, 85%, 1)', # gray-10
    'hsla(5, 94%, 73%, 1)',  # red-10
    'hsla(152, 51%, 54%, 1)', # green-10
    'hsla(43, 69%, 63%, 1)', # yellow-10
    'hsla(191, 54%, 62%, 1)', # blue-10
    'hsla(242, 52%, 69%, 1)', # violet-10
    'hsla(26, 85%, 58%, 1)', # orange-10
    'hsla(34, 31%, 68%, 1)', # gray-30
]
background = 'hsla(30, 19%, 14%, 1)' # base-10
brights = [
    'hsla(34, 39%, 74%, 1)', # gray-20
    'hsla(4, 91%, 67%, 1)',  # red-20
    'hsla(154, 57%, 42%, 1)', # green-20
    'hsla(42, 79%, 51%, 1)', # yellow-20
    'hsla(194, 59%, 56%, 1)', # blue-20
    'hsla(241, 45%, 57%, 1)', # violet-20
    'hsla(24, 84%, 50%, 1)', # orange-20
    'hsla(34, 24%, 40%, 1)', # gray-50
]
compose_cursor = 'hsla(26, 85%, 58%, 1)' # orange-10
cursor_bg = 'hsla(34, 31%, 68%, 1)' # gray-30
cursor_border = 'hsla(34, 31%, 68%, 1)' # gray-30
cursor_fg = 'hsla(30, 19%, 14%, 1)' # base-10
foreground = 'hsla(32, 48%, 85%, 1)' # gray-10
scrollbar_thumb = 'hsla(33, 27%, 30%, 1)' # gray-60
selection_bg = 'rgba(48, 50, 61, 0.5)' # converted from 50% hsla to rgba
selection_fg = 'rgba(0, 0, 0, 0)' 
split = 'hsla(34, 39%, 74%, 1)' # gray-20

[colors.indexed]

[colors.tab_bar]
background = 'hsla(30, 19%, 14%, 1)' # base-10

[colors.tab_bar.active_tab]
bg_color = 'hsla(242, 52%, 69%, 1)' # violet-10
fg_color = 'hsla(30, 19%, 14%, 1)' # base-10
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab]
bg_color = 'hsla(30, 19%, 14%, 1)' # base-10
fg_color = 'hsla(32, 48%, 85%, 1)' # gray-10
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.inactive_tab_hover]
bg_color = 'hsla(34, 39%, 74%, 1)' # gray-20
fg_color = 'hsla(32, 48%, 85%, 1)' # gray-10
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab]
bg_color = 'hsla(30, 19%, 14%, 1)' # base-10
fg_color = 'hsla(32, 48%, 85%, 1)' # gray-10
intensity = 'Normal'
italic = false
strikethrough = false
underline = 'None'

[colors.tab_bar.new_tab_hover]
bg_color = 'hsla(242, 52%, 69%, 1)' # violet-10
fg_color = 'hsla(32, 48%, 85%, 1)' # gray-10
intensity = 'Normal'
italic = true
strikethrough = false
underline = 'None'

[metadata]
aliases = []
author = 'allank'
name = 'Primary'
origin_url = 'https://github.com/allank/primary_wezterm'
